### ISSUE TITLE
日期LocalDateTime 查询报错

### ISSUE THREAD

**Issue by leet123** [baomidou/mybatis-plus#1070]
报错版本： 3.1.1

在3.1.0运行正常，升级3.1.1后，数据库字段为Date，Java字段为LocalDateTime,  数据库是oracle，查询时报异常 "Error attempting to get column 'U_EDITDATE' from result set.  Cause: java.sql.SQLFeatureNotSupportedException\n; ]; null; nested exception is java.sql.SQLFeatureNotSupportedException"

**Comment by miemieYaho** [comment]
druid 的问题

**Comment by narcissux** [comment]
> druid 的问题

你好，我也遇到了这个问题，应该怎么配置druid呢？

**Comment by miemieYaho** [comment]
druid 自身的问题

**Comment by Jiiiiiin** [comment]
@miemieYaho 如何解决呢？
哈哈

**Comment by huluobo11** [comment]
怎么解决的？？？

**Comment by qmdx** [comment]
换掉连接池为 hikaricp 因为 durid 未对最新 jdbc 类型支持

**Comment by huluobo11** [comment]
> 换掉连接池为 hikaricp 因为 durid 未对最新 jdbc 类型支持

ok. 谢谢

**Comment by cedarjo** [comment]
> 换掉连接池为 hikaricp 因为 durid 未对最新 jdbc 类型支持

Servlet.service() for servlet [dispatcherServlet] in context with path [/api] threw exception [Request processing failed; nested exception is org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.type.TypeException: Could not set parameters for mapping: ParameterMapping{property='startDate', mode=IN, javaType=class java.time.LocalDateTime, jdbcType=DATE, numericScale=null, resultMapId='null', jdbcTypeName='null', expression='null'}. Cause: org.apache.ibatis.type.TypeException: Error setting non null for parameter #5 with JdbcType DATE . Try setting a different JdbcType for this parameter or a different configuration property. Cause: java.sql.SQLException: 无效的列类型] with root cause

这是弃用druid后了

![image](https://user-images.githubusercontent.com/22877523/62347881-d1d40680-b52d-11e9-8c36-4dd67d48cf49.png)

**Comment by SouthLight-Lin** [comment]
可以尝试引入这个typeHandler 包
`<dependency>
            <groupId>org.mybatis</groupId>
            <artifactId>mybatis-typehandlers-jsr310</artifactId>
            <version>1.0.1</version>
        </dependency>`

**Comment by SouthLight-Lin** [comment]
可以尝试引入这个typeHandler 包
`
<dependency>
            <groupId>org.mybatis</groupId>
            <artifactId>mybatis-typehandlers-jsr310</artifactId>
            <version>1.0.1</version>
</dependency>
`

**Comment by zkkxyz** [comment]
升级druid到最新版本就行了，我升级到1.1.21是ok的

**Comment by kawav** [comment]
druid 升级到 1.1.21 以上之外，ojdbc 也要[升级到 8](https://mvnrepository.com/artifact/com.oracle.database.jdbc/ojdbc8/12.2.0.1)

**Comment by anuxs** [comment]
我也遇到同样的 localdatetime 字段的结果集报错问题，解决方案也是看了上面的收到启发，更换 jdbc 驱动为最新版本就解决问题了，老 jdbc 驱动不支持 localdatetime 类型。我的是 microsoft sql server 2008数据库。

<dependency>
    <groupId>com.microsoft.sqlserver</groupId>
    <artifactId>mssql-jdbc</artifactId>
    <version>8.2.2.jre8</version>
</dependency>

之前代码是用的 6.2 版本的 jdbc 驱动，太老了。另外吐槽一下百度，我在公司的开发机器上没法用 google，只能用百度，百度真是稀烂，找不到本 issue，找的全是 Csdn 上的各种不靠谱的、不相关的结果。还是 google 精准的找到答案。
当然，一贯的发现  miemieYaho  在解答问题的不耐烦，面对新手不友好，只说是 druid 的问题，可能别人搜索过来看到第一个结果是本 issue，但是你并没有说是 druid 的什么问题，可能你一天解答一千个类似问题，但是用户没有一天看一千个 issue 啊，还得去翻其他的答案，或者等着其他用户网友在下面补充，druid 的版本更新到最新就解决问题了,jdbc 升级到 8 就解决问题了。
前面我也在搜索一个 sqlsessionfactory 的问题，miemieYaho 在下面给了两个 test 的代码例子，让提问者自己去照抄，其实照抄是不对的。后面也是有其他用户在补充该怎么用。miemieYaho 对新手不太友好。当然，善用 google 是第一要求，简单问题问多了，神仙也有怒火了。
