### ISSUE TITLE
最近两个版本都不可用，求尽快发布新版本

### ISSUE THREAD

**Issue by liu-xinhui** [baomidou/mybatis-plus#3807]
3.4.3.1和3.4.3都存在导致项目无法启动的bug。

3.4.3.1 xml中如果resultMap存在嵌套，项目无法启动
3.4.3 sevice中的反射问题，导致项目无法启动

这两个问题都有很多人提过bug了，但是过去好几个月了仍未发布新版。
请求尽快发布一个修复版本

**Comment by zhuzhenwen-github** [comment]
刚刚去升级了一下3.4.3.1版本，启动报错信息是：Caused by: java.lang.ClassCastException: com.baomidou.mybatisplus.core.MybatisConfiguration$StrictMap$Ambiguity cannot be cast to org.apache.ibatis.mapping.ResultMap
分析了一下原因：
MybatisConfiguration 的checkGloballyForDiscriminatedNestedResultMaps方法类型转换的时候，没有做兼容，而不兼容的类型是Ambiguity，这个类型只有在开启了useGeneratedShortKey的时候才会有，默认是开启的，所以只需要关闭这个短key缓存就可以解决这个类型转换的问题。
 @Bean
    public ConfigurationCustomizer configurationCustomizer() {
        return configuration -> configuration.setUseGeneratedShortKey(false);
    }

**Comment by qmdx** [comment]
版本 `3.4.3.2` 已发布，请升级验证修复该问题，有任何问题 issue 该问题关闭！
