### ISSUE TITLE
findIDialect sql server2012判断错误

### ISSUE THREAD

**Issue by linyouq** [baomidou/mybatis-plus#3951]
### 当前使用版本(必填,否则不予处理)
3.4.3.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
![](https://s3.bmp.ovh/imgs/2021/09/f0c7350f90896f1e.png)
sqlserver2012 的 地址 并不是 :sqlserver2012:
现在的判断会导致 SQL server都是用旧版分页

**Comment by huayanYu** [comment]
那是什么啊

**Comment by linyouq** [comment]
jdbc:microsoft:sqlserver:  是旧版的
jdbc:sqlserver: 是新版的。（至少我现在程序用的连接url是这个，然后用2012的分页）

**Comment by code-farmhand** [comment]
你这段代码是哪里的？

**Comment by code-farmhand** [comment]
@linyouq 我的 SQL Server 版本:  Microsoft SQL Server 2019 (RTM-CU12) (KB5004524) - 15.0.4153.1 (X64) 
## 如果分页插件使用 `DbType.SQL_SERVER` 
###  不添加 order by 会触发以下错误
‘’‘
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT  id,code,name,del_flag  FROM area_code   WHERE del_flag IS NULL OFFSET ? ROWS FETCH NEXT ? ROWS ONLY
### Cause: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near 'OFFSET'.
; uncategorized SQLException; SQL state [S0001]; error code [102]; Incorrect syntax near 'OFFSET'.; nested exception is com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near 'OFFSET'.] with root cause
’‘’
### 添加 order by 后可用
## 使用 `DbType.SQL_SERVER2005` 就没有问题
无论是否有 order  by 都正常

**Comment by linyouq** [comment]
### 我是想说明我截图的那段代码是错误的。

至于@code-farmhand 

问题不是使用SQL Server 2012 提供的新分页的时候会报错。必须与 order by 组合使用没毛病。
问题在于，
多数据源多类型数据库的时候。框架判断DbType 是 DbType.SQL_SERVER2005
不是哪个能用的问题。是判断的逻辑出错了。

单个数据数据源想用哪个就设置哪个。
多个不同类型数据源，SQL SERVER 数据源就要使用 DbType.SQL_SERVER 对应的分页 就只能重写相应代码。

或者有什么办法能直接指定不同数据源使用的分页方言？

**Comment by code-farmhand** [comment]
@linyouq 目前来讲，针对SQL Server 的成熟的分页就是目前 `DbType.SQL_SERVER2005` 对应的方言实现，不论是针对原生 mybatis 的 pagehelper 插件，还是非 Mybatis 体系的Spring Data JPA， 都是采用的同样的SQL 语法结构(第1页有的框架用top)。
分页绑定 order by， 从插件实现的角度来讲有一定的困难，因为用任意的字段排序，都是不是原来的默认排序，当开发者未指定排序字段时，分页的先后顺序就应该是数据库的默认返回，框架自动补充哪个真实的表字段都是错的。
从框架实现角度来讲，使用 `DbType.SQL_SERVER2005` 才是通用的选择。从这个角度考虑，我不认为你贴出的代码是错的。

关于多数据源的情况，非要指定某一数据源使用 `DbType.SQL_SERVER` ， 目前只有重写分页，或者从 SessionFactory 上动手。

**Comment by qmdx** [comment]
欢迎 pr
